### ISSUE TITLE
An option to remove the plugin from elements should be provided

### ISSUE THREAD

**Issue by marcolz** [wedgies/jquery-emoji-picker#30]
```javascript
$('.picker').emojiPicker('destroy');
```

**Comment by jenwilhelm** [comment]
@marcolz I think I might tackle this one... do you have a specific use case for how this would be useful?

**Comment by marcolz** [comment]
I don't recall exactly as it's something that I needed months ago. But I found having a `destroy` options to be a common pattern for jQuery plugins.

**Comment by r3wt** [comment]
@jenwilhelm I develop an SPA framework for use with jQuery. it cleans up all bound events by acting as a proxy to `jQuery.fn.init` and keeping track of elements with bound events, but can't clean up anything inside of the plugin. Currently, emoji picker functions normally without a destroy method in my app, but i'm not sure if there is memory leaking anywhere. other plugins, like some of the plugins in bootstrap and foundation do leak memory due to lack of a destroy method. a destroy method can ensure that it doesn't. In this app, there are two functions used to bind events . `bind(namespace,callable)` and `bindOnce(callable)`. these work like an instance of document ready, more or less. the developer signals the app is ready by calling `done()` method. this is where all previously bound events are destroyed, and new events are bound. an example of this timeline is listed below.:

![img](http://puu.sh/mLdOs/3cb9260716.png)

currently i am using the emoji picker as so. since its not needed globally, it is instantiated via `bindOnce`. currently the only way to do manual destruction is to `listenOnce` on `before.go`, however in the future i will probably provide and `unbind` method to add this option into the framework.
```js
$.jqMVC.bindOnce(function(){
    if($('link[href="'+location.origin+'/dist/emoji.tw.css"]').length == 0){
        var l = document.createElement('link'); 
        l.rel = 'stylesheet';
        l.href = location.origin+'/dist/emoji.tw.css';
        var h = document.getElementsByTagName('head')[0]; h.parentNode.insertBefore(l, h);
    }
    $('#status-p').emojiPicker({
      height: '247px',
      width: '485px',
      button: false
    }); 
    $(document).on('click','#emoji-pick',function(e){
        e.preventDefault();
        $('#status-p').emojiPicker('toggle');
        return false;
    });
    $.jqMVC.listenOnce('before.go',function(){
        //listen before the router navigates and destroys plugin
    });
})
```

hopefully this post highlights how immensely useful a destruction function is if it can't be insured that emojipicker does not leak memory. i haven't profiled emoji picker specifically but most of the plugins i've profiled do leak memory to some extent. some correctly authored plugins do not.

**Comment by zpnk** [comment]
@marcolz @r3wt I have opened a PR adding a destroy option. See #40. Your feedback would be appreciated on the api and cleanup behavior.
