### ISSUE TITLE
wap is not

### ISSUE THREAD

**Issue by 7733012** [wedgies/jquery-emoji-picker#54]
iphone is wrong

**Comment by vishnu1991** [comment]
Can u please describe it more clearly!?

**Comment by makenai** [comment]
Since emoji input is already available on mobile devices including iphones, this software is disabled on iOS intentionally so it doesn't confuse users. If you want to force it to work on iOS you might need to change the line here:

https://github.com/wedgies/jquery-emoji-picker/blob/master/js/jquery.emojipicker.js#L68
